town: hello town config
spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/town?characterEncoding=utf-8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
